---
title: "Week 3"
output: html_document
author: "Frida van Teijlingen"
---
# Assignments during class

## Packages
```{r}
# start with clean workspace
rm(list = ls())

#install.packages('data.table')
library(data.table)  # mainly for faster data handling
library(tidyverse)  # I assume you already installed this one!
#install.packages('httr') # we don't need this for now require(httr)
#install.packages("xml2")
require(xml2)
#install.packages("rvest")
require(rvest)
#install.packages("devtools")
require(devtools)
# Note we're doing something different here. We're installing a *latest* version directly from
# GitHub This is because the released version of this packages contains some errors!
devtools::install_github("jkeirstead/scholar")

require(scholar)

# define workdirectory, note the double *backslashes* if you're on windows setwd('/yourpathhere)'
setwd('C:/Users/frida/OneDrive/Documenten/RADBOUD researchmaster/P1 Social networks')

```


## Finding a data source
```{r}
# Let's first get the staff page read_html is a function that simply extracts html webpages and
# puts them in xml format
#soc_staff <- read_html("https://www.ru.nl/sociology/research/staff/")

#error! because old website --> use the wayback machine to retrieve the old website

soc_staff <- read_html("https://web.archive.org/web/20230528153336/https://www.ru.nl/sociology/research/staff/")
head(soc_staff)
#What type of object did we store it by putting the html into soc_staff?

class(soc_staff)
```
## finding the right html elements and rvest
```{r}
# so we need to find WHERE the table is located in the html 'inspect element' in mozilla firefox or
# 'view page source' and you see that everything AFTER /td in the 'body' of the page seems to be
# the table we do need




#install.packages('selectr')
library(selectr)


# wihtout xml2 things but using html_elements because that is in the same package, sloppy programming to mix different programming languages 
soc_staff <- soc_staff %>%
    rvest::html_elements("body") %>%
    rvest::html_elements("td") %>%
    rvest::html_text()
soc_staff

soc_staff <- read_html("https://web.archive.org/web/20230528153336/https://www.ru.nl/sociology/research/staff/")
head(soc_staff)

#trying to get a table from the website
soc_staff <- soc_staff %>%
    rvest::html_elements("body") %>%
    rvest::html_table()  
soc_staff



```
## Number of people on the list
```{r}
fodd <- function(x) x%%2 != 0
feven <- function(x) x%%2 == 0

nstaf <- length(soc_staff)
nstaf

 # Do you understand why we need the nstaf? What it does?
soc_names <- soc_staff[fodd(1:nstaf)]  # in the 1 until 94st number, get the odd elements
head(soc_names)
```
## Looking for all names of Leiden Political science
```{r}
leidse_staff <- read_html("https://www.universiteitleiden.nl/en/social-behavioural-sciences/political-science/staff#tab-1")
head(leidse_staff)
#What type of object did we store it by putting the html into soc_staff?

class(leidse_staff)


#
leidse_staff <- leidse_staff %>%
    rvest::html_elements("body") %>%
    rvest::html_elements("a") %>%
    rvest::html_text()
leidse_staff


#when including the things below you select to little info, can do this separately, and combine the names (strong) and function (span)
#    rvest::html_elements("strong") %>%
#    rvest::html_elements("span") %>%
```

## RSelenium
```{r}
#RSelenium usefull for websites where the data is 'loaded in', rvest cant handle that
#packages: "RSelenium", "rvest", "tidyverse", "netstat", "pingr", "stringr"
#install.packages("RSelenium")
#install.packages("netstat")
#install.packages("pingr")

library(RSelenium)
library(rvest)
library(tidyverse)
library(netstat)
library(pingr)
library(stringr)
```

## OpenAlex
```{r}
#install.packages("openalexR")
library(openalexR)


df <- oa_fetch(entity= "author", search = "Jochem+Tolsma", mailto = "fridakooptdingen@gmail.com")
df
#send to email, wont really send it to my mail but lifts some limitations


df_papers <-oa_fetch(entity = "works", author.id = df$id)
df_papers$author[1]

#zoek institution ID
options(openalexR.mailto = "fridakooptdingen@gmail.com")
df_institution <- oa_fetch(entity = "institutions", search = "Radboud+University+Nijmegen")$id[1]
df_institution


oa_fetch(entity = "author", search = "Jochem Tolsma", affiliations.institution.id = "https://openalex.org/I145872427")


```
## Compiling a network

```{r}
#network in elkaar zetten
options(openalexR.mailto = "fridakooptdingen@gmail.com")
 
#Jochem
id1<- oa_fetch(entity = "author", search = "Jochem Tolsma", affiliations.institution.id = "https://openalex.org/I145872427")


#Tom van der Meer
#id van UvA
#oa_fetch(entity = "institutions", search = "University of Amsterdam")$id[1]
#was de eerste, gecheckt via openalex	

id2<- oa_fetch(entity = "author", search = "Tom van der Meer", affiliations.institution.id = "https://openalex.org/I887064364")
id2 <- id2[1,]

#Maurice Gesthuizen
id3<- oa_fetch(entity = "author", search = "Maurice Gesthuizen", affiliations.institution.id = "https://openalex.org/I145872427")

#Michael Savelkoul
id4<- oa_fetch(entity = "author", search = "Michael Savelkoul", affiliations.institution.id = "https://openalex.org/I145872427")

all_id <- c(id1$id, id2$id, id3$id, id4$id)
all_id 

worksJT<- oa_fetch(entity = "works", author.id = id1$id)
worksTVDM<- oa_fetch(entity = "works", author.id = id2$id)
worksMG<- oa_fetch(entity = "works", author.id = id3$id)
worksMS<- oa_fetch(entity = "works", author.id = id4$id)

all_works <- rbind(worksJT, worksTVDM)
all_works <- rbind(all_works, worksMG)
all_works <- rbind(all_works, worksMS)
View(all_works)

wave1 <- matrix(0, nrow=4, ncol=4)
wave1

attributes(all_works)
library(tidyverse)
all_works_1 <- filter(all_works, publication_year >= 2016)
all_works_1 <- filter(all_works_1, publication_year <= 2020)
View(all_works_1)

rownames(wave1)<- c(id1$id, id2$id, id3$id, id4$id)
colnames(wave1)<- c(id1$id, id2$id, id3$id, id4$id)
wave1

#selecting first row of large datafile, when loop use 'i' instead of '1'
ego <- all_works_1[1,]$author[[1]]$au_id[1]
ego
#%in% To determine whether a specific value is present in a column of an R data frame
alter <- all_works_1[1,]$author[[1]]$au_id[-1][all_works_1[1,]$author[[1]]$au_id[-1] %in% all_id]
alter 
wave1[ego, alter] <- 1

wave1








```

