---
title: "Week 7 lecture"
author: "by: Frida van Teijlingen"
bibliography: references.bib
---
# Set up
```{r}
rm(list = ls())

#---- Loading packages ----
fpackage.check <- function(packages) {
    lapply(packages, FUN = function(x) {
        if (!require(x, character.only = TRUE)) {
            install.packages(x, dependencies = TRUE)
            library(x, character.only = TRUE)
        }
    })
}

#---- Data saving ----
fsave <- function(x, file = NULL, location = "./data/processed/") {
    ifelse(!dir.exists("data"), dir.create("data"), FALSE)
    ifelse(!dir.exists("data/processed"), dir.create("data/processed"), FALSE)
    if (is.null(file))
        file = deparse(substitute(x))
    datename <- substr(gsub("[:-]", "", Sys.time()), 1, 8)
    totalname <- paste(location, file, "_", datename, ".rda", sep = "")
    save(x, file = totalname)  #need to fix if file is reloaded as input name, not as x. 
}

#---- Loading in data ----
fload <- function(filename) {
    load(filename)
    get(ls()[ls() != "filename"])
}

#---- Output ----
fshowdf <- function(x, ...) {
    knitr::kable(x, digits = 2, "html", ...) %>%
        kableExtra::kable_styling(bootstrap_options = c("striped", "hover")) %>%
        kableExtra::scroll_box(width = "100%", height = "300px")
}

```

# Libraries
```{r}
packages <- c("")
fpackage.check(packages)
```

#Data
```{r}
#df_ego
#df_ego <- fload("./data/processed/df_ego_20241009.rda")

#df_works
#df_works <- fload("data/processed/df_works_20241009.rda")

#df_allunis
#unidata <- fload("data/processed/unidata_20241007.rda")

#travelt_matrix <- fload("data/processed/travelt_matrix20241009")
```

